application:
  name: simple-example-vertx
  project: vertx-example
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
- name: main
  routes:
  - application_name: simple-example-vertx
    paths:
    - /*
